# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 1.添加模块所在路径
flutter_application_path = '../jp_flutter_module' # jp_flutter_module 位于 Podfile 文件的上一级位置
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'JPFlutterModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 2.安装Flutter模块
  install_all_flutter_pods(flutter_application_path)
  
  pod 'lottie-ios'
  pod 'LookinServer', :configurations => ['Debug']

  # Pods for JPFlutterModule

end
